In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import os as os
import re


pd.set_option('display.max_colwidth',700)
pd.set_option('display.max_columns',None)

os.listdir('/content/drive/MyDrive/Colab Notebooks/Supervised Learning/WhatsApp Chat Analysis/')

["what's_chat_analysis.ipynb",
 'WhatsApp Chat with Competitive Programmers.txt']

In [ ]:

path = '/content/drive/MyDrive/Colab Notebooks/Supervised Learning/WhatsApp Chat Analysis/WhatsApp Chat with Competitive Programmers.txt'


with open(path, encoding='utf-8') as file:
  file_data = file.read()


len(file_data)

1597604

In [ ]:
file_data

'10/6/20, 7:09\u202fPM - Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. *Learn more*\n1/28/20, 9:45\u202fPM - +91 94088 93107 created group "Competitive Programmers"\n10/6/20, 7:09\u202fPM - You joined using this group\'s invite link\n10/6/20, 7:10\u202fPM - +91 72928 89444: yes\n10/6/20, 7:10\u202fPM - +91 72928 89444: C. option\n10/6/20, 7:10\u202fPM - +91 72928 89444: O(nlogn)\n10/6/20, 7:12\u202fPM - +91 72928 89444: how n^2 bhaia\n10/6/20, 7:13\u202fPM - +91 72928 89444: <Media omitted>\n10/6/20, 8:03\u202fPM - +91 70115 09528: bhai koi h yha pe jo codechef pe practice krta ho or NZEC  error ajate h hr program m uska ya na ae to wrong answr ata h\n10/6/20, 8:09\u202fPM - +91 72928 89444: question no\n10/6/20, 8:20\u202fPM - +91 98499 81675: B\n10/6/20, 8:26\u202fPM - +91 98347 58456: Ohh... This is right\n10/6/20, 8:29\u202fPM - +91 95407 65311: #include <iostream>\nusing namespace std;\n\nint main() {\n    int t;\n    cin>>t;\n    while(t--){\n        long long int n,k;\n        cin>>n>>k;\n        int arr[1000];\n        for (int i=0;i<n;i++){\n            cin>>arr[i];\n        }\n        \n        for(int i=0;i<n;i++){\n            if(arr[i]%k==0){\n                cout<<\'1\';\n            }\n            else{\n                cout<<\'0\';\n            }\n        }\n    }\n\treturn 0;\n}\n10/6/20, 8:29\u202fPM - +91 95407 65311: whats wrong with this code?\n10/6/20, 8:29\u202fPM - +91 95407 65311: cant find any error but there is apparently\n10/6/20, 8:30\u202fPM - +91 95407 65311: https://www.codechef.com/problems/CHEFSTEP\n10/6/20, 8:30\u202fPM - +91 95407 65311: for this problem\n10/6/20, 8:30\u202fPM - +91 63044 49114: Cout << "1"\n10/6/20, 8:30\u202fPM - +91 95407 65311: yeah tried thst too\n10/6/20, 8:31\u202fPM - +91 95407 65311: #include <iostream>\nusing namespace std;\n\nint main() {\n    int t;\n    cin>>t;\n    while(t--){\n        long long int n,k;\n        cin>>n>>k;\n        int arr[1000];\n        for (int i=0;i<n;i++){\n            cin>>arr[i];\n        }\n        \n        for(int i=0;i<n;i++){\n            if(arr[i]%k==0){\n                cout<<"1";\n            }\n            else{\n                cout<<"0";\n            }\n        }\n    }\n\treturn 0;\n}\n10/6/20, 8:31\u202fPM - +91 95407 65311: still giving wromg ans\n10/6/20, 8:31\u202fPM - +91 63044 49114: What is the error your getting\n10/6/20, 8:31\u202fPM - +91 63044 49114: Than check ur logic\n10/6/20, 8:31\u202fPM - +91 95407 65311: wrong ans\n10/6/20, 8:31\u202fPM - +91 95407 65311: ya got it, i forgot putting /n in the end\n10/6/20, 9:45\u202fPM - +91 77022 56610: Did u made it with flutter bro\n10/6/20, 10:31\u202fPM - +91 98059 60584: Yes\n10/6/20, 10:44\u202fPM - +234 815 971 8137: Hi\n10/6/20, 10:45\u202fPM - +91 91238 47093: Hii\n10/6/20, 10:45\u202fPM - +91 91238 47093: How you guys manage both dev and CP?\n10/7/20, 8:41\u202fAM - +91 81306 58552 was added\n10/6/20, 10:45\u202fPM - +91 81306 58552: DM to buy any premium accounts in cheapest rates.\n*(Accounts like :- LeetCode , Netflix , Amazon Prime and many more)*\n\n\nhttps://chat.whatsapp.com/IM9u21HdXqT54H4HokQ2vx\n\nJoin for more exciting offers.\n10/6/20, 10:45\u202fPM - +234 815 971 8137: Just create time...\n10/6/20, 10:46\u202fPM - +91 91238 47093: Normally I get max to max 5 hours after college\n10/6/20, 10:48\u202fPM - +234 815 971 8137: Just break it down ....2 for web dev then u rest for 1 hour then the other 2 for cp\n10/6/20, 10:49\u202fPM - +234 815 971 8137: Or u can use 1 and half hour each and use d remaining 2 hours for rest\n10/6/20, 10:49\u202fPM - +91 91238 47093: Okk\n10/6/20, 10:49\u202fPM - +91 91238 47093: Where are you from?\n10/6/20, 10:50\u202fPM - +91 72928 89444: me 3 hrs\n10/6/20, 10:50\u202fPM - +91 72928 89444: 8am to 6 pm😖\n10/6/20, 10:55\u202fPM - +91 91238 47093: Sad🥺🥺🥺🥺\n10/7/20, 8:41\u202fAM - +91 81306 58552 left\n10/6/20, 10:56\u202fPM - +91 91238 47093: I come home by 5 pm start studying from 6:30 to 12:00\n10/6/20, 10:57\u202fPM - +91 72928 89444: 🤩👍 great\n10/6/20, 10:57\u202fPM - +91 91238 47093: And 10:00 to 10:30 dinner\n10/6/20, 10:57\u202fPM - +91 72928 89444: i give 3hrs for coding and 3 hrs for cgpa😅\n10/6/20, 10:58\u202fPM - +91 72928 89444: <Media omitted>\n10/6/20, 10:58\u202fPM - +91 72928 89444: adding sq one\n10/6/20, 10:59\u202fPM - +91 72928 89444: just give me little hint\n10/6/20, 11:00\u202fPM - +91 72928 89444: whether the complexity of problem could be less that n^2 or not\n10/6/20, 11:00\u202fPM - +91 72928 89444: anyone doing CodeChef  long challenge\n10/6/20, 11:02\u202fPM - +91 72928 89444: This message was deleted\n10/6/20, 11:02\u202fPM - +91 72928 89444: https://www.codechef.com/OCT20B/problems/ADDSQURE\n10/6/20, 11:06\u202fPM - +91 91238 47093: You study everyday for college studies!!!😶😶\n10/6/20, 11:24\u202fPM - +91 81306 58552 left\n10/7/20, 12:11\u202fAM - +91 95407 65311: Anyone who has done the second question of long challenge and is awake?\n10/7/20, 1:03\u202fAM - +91 72928 89444: Alice and Bob have decided to play the game "Rock, Paper, Scissors".\n\nThe game consists of several rounds, each round is independent of each other. In each round, both players show one of the following things at the same time: rock, paper or scissors. If both players showed the same things then the round outcome is a draw. Otherwise, the following rules applied:\n\nif one player showed rock and the other one showed scissors, then the player who showed rock is considered the winner and the other one is considered the loser;\nif one player showed scissors and the other one showed paper, then the player who showed scissors is considered the winner and the other one is considered the loser;\nif one player showed paper and the other one showed rock, then the player who showed paper is considered the winner and the other one is considered the loser.\nAlice and Bob decided to play exactly n rounds of the game described above. Alice decided to show rock a1 times, show scissors a2 times and show paper a3 times. Bob decided to show rock b1 times, show scissors b2 times and show paper b3 times. Though, both Alice and Bob did not choose the sequence in which they show things. It is guaranteed that a1+a2+a3=n and b1+b2+b3=n.\n\nYour task is to find two numbers:\n\nthe minimum number of round Alice can win;\nthe maximum number of rounds Alice can win.\nInput\nThe first line of the input contains one integer n (1≤n≤109) — the number of rounds.\n\nThe second line of the input contains three integers a1,a2,a3 (0≤ai≤n) — the number of times Alice will show rock, scissors and paper, respectively. It is guaranteed that a1+a2+a3=n.\n\nThe third line of the input contains three integers b1,b2,b3 (0≤bj≤n) — the number of times Bob will show rock, scissors and paper, respectively. It is guaranteed that b1+b2+b3=n.\n\nOutput\nPrint two integers: the minimum and the maximum number of rounds Alice can win.\n10/7/20, 1:03\u202fAM - +91 72928 89444: 686\n479 178 29\n11 145 530\noutputCopy\n22 334\n10/7/20, 1:03\u202fAM - +91 72928 89444: <Media omitted>\n10/7/20, 1:03\u202fAM - +91 72928 89444: Try this\n10/7/20, 1:03\u202fAM - +91 72928 89444: Yes\n10/7/20, 1:04\u202fAM - +91 72928 89444: <Media omitted>\n10/7/20, 1:05\u202fAM - +91 72928 89444: Till 4th done\n10/7/20, 1:05\u202fAM - +91 72928 89444: 6th only thought\n10/7/20, 1:05\u202fAM - +91 72928 89444: But it\'s very lengthy\n10/7/20, 6:29\u202fAM - +91 98347 58456: N**2 works here\n10/7/20, 6:29\u202fAM - +91 98347 58456: For partial marks\n10/7/20, 6:30\u202fAM - +91 98347 58456: I hv done it\n10/7/20, 6:33\u202fAM - +91 72928 89444: 🤩👍\n10/7/20, 6:53\u202fAM - +91 77022 56610: Bro where u learnt it\n10/7/20, 7:33\u202fAM - +91 63697 84632: write a series of python statement that will first as the user to type today\'s exchange rate between US dollars and Euro next as the user to type a value in dollars finally print the equivalentvalue in euros\n10/7/20, 7:33\u202fAM - +91 63697 84632: Anyone give the solution for this\n10/7/20, 7:48\u202fAM - +91 72928 89444: <Media omitted>\n10/7/20, 7:48\u202fAM - +91 72928 89444: Just do unity method\n10/7/20, 9:08\u202fAM - +91 90493 80183: Where can I learn theory of computation??? On youtube\n10/7/20, 9:08\u202fAM - +91 90493 80183: Which YouTube videos are good\n10/7/20, 9:14\u202fAM - +91 95220 34949: Sanchit is best for T.O.C\n10/7/20, 9:14\u202fAM - +91 95220 34949: Knowledge Gate channel\n10/7/20, 9:14\u202fAM - +91 90493 80183: Okay👍\n10/7/20, 9:16\u202fAM - +91 99100 53699: 10^5 mein O(n) will give tle?\n10/7/20, 9:19\u202fAM - +91 70461 77123: No\n10/7/20, 10:24\u202fAM - +91 92679 77407 left\n10/7/20, 11:10\u202fAM - +91 95550 70785: easy bro..........\n10/7/20, 11:10\u202fAM - +91 95550 70785: #include <iostream>\nusing namespace std;\n\n\nint main()\n{\n    cout << "Hello World!\\n";\n    cout << "hello sir would you please let me know the value of 1 dollar in euros";\n    int  cash_d;\n    float rate,cash_e;\n    cin >> rate;\n    cout << "enter amount of dollar to convert it in euros";\n    cin >> cash_d;\n    cash_e = cash_d / rate;\n    cout << "your " << cash_d << " dollars in euros are" << cash_e;\n}\n10/7/20, 11:10\u202fAM - +91 95550 70785: i have just made it a little user friendly by adding some statements u can remove it though\n10/7/20, 11:44\u202fAM - +91 87896 62257 joined using a group link.\n10/7/20, 11:48\u202fAM - +91 99032 73301: <Media omitted>\n10/7/20, 12:00\u202fPM - +91 72928 89444: Yes😅\n10/7/20, 12:00\u202fPM - +91 72928 89444: <Media omitted>\n10/7/20, 12:00\u202fPM - +91 72928 89444: If n is no. Of vertices\n10/7/20, 12:01\u202fPM - +91 72928 89444: Q8.\n10/7/20, 12:01\u202fPM - +91 77758 75403: Bhai ye konse subject ka hai\n10/7/20, 12:02\u202fPM - +91 72928 89444: <Media omitted>\n10/7/20, 12:02\u202fPM - +91 72928 89444: Q9,b part\n10/7/20, 12:02\u202fPM - +91 72928 89444: Or bhaia,\n Q9,a part thoda explain kijiye\n10/7/20, 12:02\u202fPM - +91 72928 89444: Wo question smjh nhi aa rha\n10/7/20, 12:03\u202fPM - +91 72928 89444: Q9 b.)²\n10/7/20, 12:03\u202fPM - +91 72928 89444: 2 is ans\n10/7/20, 12:03\u202fPM - +91 77758 75403: 👆🏻\n10/7/20, 12:03\u202fPM - +91 72928 89444: Discrete mathematics\n10/7/20, 12:03\u202fPM - +91 77758 75403: Okay\n10/7/20, 12:03\u202fPM - +91 77758 75403: Programming related topic haina\n10/7/20, 12:03\u202fPM - +91 72928 89444: Coding k liye important h,\nLogical subject h\n10/7/20, 12:03\u202fPM - +91 94205 81813: Ohh\n10/7/20, 12:04\u202fPM - +91 72928 89444: Mast logic lagta h isse, help milta h\n10/7/20, 12:04\u202fPM - +91 77758 75403: Okay mai diploma ka student hu to ye subject kar sakta kya ab\n10/7/20, 12:04\u202fPM - +91 72928 89444: Jaise no. Of rectangle made from 8 lines\n10/7/20, 12:04\u202fPM - +91 72928 89444: Are bhai subject padhne k liye degree kahan important h\n10/7/20, 12:04\u202fPM - +91 72928 89444: 🤩\n10/7/20, 12:05\u202fPM - +91 72928 89444: Araam se padh sakte h\n10/7/20, 12:05\u202fPM - +91 72928 89444: 😇👍\n10/7/20, 12:05\u202fPM - +91 72928 89444: Maza ayega\n10/7/20, 12:05\u202fPM - +91 72928 89444: Isme\n10/7/20, 12:05\u202fPM - +91 77758 75403: Okay thanks😁\n10/7/20, 12:05\u202fPM - +91 77758 75403: Links hai kya\n10/7/20, 12:05\u202fPM - +91 94205 81813: Sounds great🙄\n10/7/20, 12:05\u202fPM - +91 72928 89444: Paheli type lagta h😅\n10/7/20, 12:05\u202fPM - +91 77758 75403: Kuch aapke pass\n10/7/20, 12:05\u202fPM - +91 72928 89444: Coursera I\'d h\n10/7/20, 12:05\u202fPM - +91 72928 89444: Du apko?\n10/7/20, 12:05\u202fPM - +91 77758 75403: Ha dedo\n10/7/20, 12:05\u202fPM - +91 72928 89444: 70 courses enrolled h\n10/7/20, 12:05\u202fPM - +91 72928 89444: 😅\n10/7/20, 12:06\u202fPM - +91 72928 89444: Link vejta hu\n10/7/20, 12:06\u202fPM - +91 72928 89444: Personally\n10/7/20, 12:06\u202fPM - +91 77758 75403: Ha okay\n10/7/20, 12:06\u202fPM - +91 72928 89444: Ap kon se yr  m h\n10/7/20, 12:06\u202fPM - +91 77758 75403: 3rd year\n10/7/20, 12:06\u202fPM - +91 72928 89444: 🙏\n10/7/20, 12:07\u202fPM - +91 72928 89444: 3sem m hu abhi,hume to start hi krwaya gya h\n10/7/20, 12:07\u202fPM - +91 72928 89444: Ap kisi aur knowledgeable bhaia se guide le liye\n10/7/20, 12:07\u202fPM - +91 72928 89444: Mere pas khud adha knowledge h😅\n10/7/20, 12:07\u202fPM - +91 72928 89444: Waise link vejta hu apko👍\n10/7/20, 12:07\u202fPM - +91 77758 75403: Okay 👍 aap Coursera ke courses bhej dijiye\n10/7/20, 12:07\u202fPM - +91 77758 75403: Ha thanks 😊\n10/7/20, 12:08\u202fPM - +91 72928 89444: 😇🙏\n10/7/20, 12:08\u202fPM - +91 72928 89444: Are main junior hu\n10/7/20, 12:08\u202fPM - +91 72928 89444: 😂\n10/7/20, 12:09\u202fPM - +91 77758 75403: Aap ye khud kar rahe hai ki college walo ne info di\n10/7/20, 12:09\u202fPM - +91 77758 75403: Hame college wale itni info nahi dete\n10/7/20, 12:09\u202fPM - +91 72928 89444: Ap GitHub students I\'d k through le sakte h\n10/7/20, 12:09\u202fPM - +91 77758 75403: Cp ke baare mai\n10/7/20, 12:09\u202fPM - +91 72928 89444: Bs college I\'d k request kijiye ap college se\n10/7/20, 12:09\u202fPM - +91 72928 89444: Fir us I\'d se\n10/7/20, 12:10\u202fPM - +91 72928 89444: 1. Microsoft 365\n2. GitHub students pack\n3. Amzaon students pack\n10/7/20, 12:10\u202fPM - +91 72928 89444: Sab free🤩\n10/7/20, 12:10\u202fPM - +91 72928 89444: Bohot kaam k h student id\n10/7/20, 12:10\u202fPM - +91 77758 75403: Okay 👍 try karna padega\n10/7/20, 12:10\u202fPM - +91 72928 89444: 😇hmm\n10/7/20, 12:12\u202fPM - +91 70461 77123: + coursera courses.\n10/7/20, 12:13\u202fPM - +91 72928 89444: Ab nhi 30 September tak hi tha\n10/7/20, 12:13\u202fPM - +91 70461 77123: Oh🤕\n10/7/20, 12:13\u202fPM - +91 72928 89444: Maine isi liye 70+ courses enroll kr liya tha\n10/7/20, 12:13\u202fPM - +91 72928 89444: 😅\n10/7/20, 12:13\u202fPM - +91 72928 89444: Ab 2 mahine tak padh sakte h\n10/7/20, 12:13\u202fPM - +91 72928 89444: Don\'t worry password v de dunga\n10/7/20, 12:14\u202fPM - +91 72928 89444: Agar chahiye to\n10/7/20, 12:14\u202fPM - +91 72928 89444: <Media omitted>\n10/7/20, 12:16\u202fPM - +91 72928 89444: <Media omitted>\n10/7/20, 12:16\u202fPM - +91 99032 73301: Bhai exam me likhna hai kal exam le rha clg wala assignment based so thoda bna ke do na jo direct chap du 😁🙏🙏 padha nai hu ye topic aur tym v nai h isly\n10/7/20, 12:16\u202fPM - +91 70461 77123: Mere pas bhi id ha\nApril May tak kiya badme 6od diya\n10/7/20, 12:17\u202fPM - +91 72928 89444: Oo to padh to free m sakte h, bs certificate k liye pay krna padta h\n10/7/20, 12:17\u202fPM - +91 72928 89444: Bs knowledge k liye padhiye, certificate kya kijiyega waise v\n10/7/20, 12:17\u202fPM - +91 72928 89444: Free h\n10/7/20, 12:17\u202fPM - +91 72928 89444: Enroll kr lijiyega\n10/7/20, 12:17\u202fPM - +91 72928 89444: Bhaia direct ans hi likhna h\n10/7/20, 12:18\u202fPM - +91 77758 75403: Financial aid option hoga\n10/7/20, 12:18\u202fPM - +91 77758 75403: Na bro\n10/7/20, 12:18\u202fPM - +91 70461 77123: Coursera course bas start krne ke liye h...\nBadme useful nai lagta.\n10/7/20, 12:18\u202fPM - +91 72928 89444: Apko agar samjh n derivation to ,call kijiye main samjhane k try krunga\n10/7/20, 12:18\u202fPM - +91 72928 89444: Ha,direct likha hua ayega,learn without certificate\n10/7/20, 12:19\u202fPM - +91 72928 89444: Ha book ya online sites bata deta hu\n10/7/20, 12:19\u202fPM - +91 95550 70785: Someone please send me best course for git and GitHub\n10/7/20, 12:19\u202fPM - +91 70461 77123: Means full beginers ho tab course krke sikh lene ka.badme to khud hi krna padta h\n10/7/20, 12:19\u202fPM - +91 72928 89444: Fir wo bana lijiyega\n10/7/20, 12:19\u202fPM - +91 72928 89444: Ok\n10/7/20, 12:20\u202fPM - +91 72928 89444: [FreeCourseSite.com] Udemy - The Complete 2020 Web Development Bootcamp\n10/7/20, 12:19\u202fPM - +91 87896 62257 left\n10/7/20, 12:20\u202fPM - +91 72928 89444: <Media omitted>\n10/7/20, 12:21\u202fPM - +91 72928 89444: Is mahila ne sikhaya h,\n10/7/20, 12:21\u202fPM - +91 72928 89444: Isse sikh sakte h\n10/7/20, 12:21\u202fPM - +91 72928 89444: Ye download link h\n10/7/20, 12:21\u202fPM - +91 72928 89444: Search kijiye\nhttp://FreeCourseSite.com\n10/7/20, 12:21\u202fPM - +91 72928 89444: Is site p\n10/7/20, 12:22\u202fPM - +91 95550 70785: It tells all about git and GitHub?\n10/7/20, 12:22\u202fPM - +91 72928 89444: 👍sahi baat , practice to khud se hi krna padta h\n10/7/20, 12:22\u202fPM - +91 72928 89444: Aur v bohot sara\n10/7/20, 12:22\u202fPM - +91 95550 70785: Oh okay thanks 😃\n10/7/20, 12:22\u202fPM - +91 72928 89444: Ye v ek part h isme\n10/7/20, 12:23\u202fPM - +91 72928 89444: 👍\n10/7/20, 12:23\u202fPM - +91 72928 89444: Carrierride.com\nGeeksforgeeks.com\nCompscibits.com\nLearnerindia.com\nGkseries.com\nCs-mcqs.blogspot.com\n10/7/20, 12:24\u202fPM - +91 72928 89444: Ye sab site solve kijiye, \nAche h sare😅\n10/7/20, 12:29\u202fPM - +91 73554 80774: Is codeforces down?\n10/7/20, 12:29\u202fPM - +91 90742 07335: Yup\n10/7/20, 12:30\u202fPM - +91 72928 89444: Kl raat 2 bje se hi h😪\n10/7/20, 12:30\u202fPM - +91 72928 89444: 3 bje tk try kiye fir soo gye\n10/7/20, 12:30\u202fPM - +91 72928 89444: Abhi tk nhi thik hua?\n10/7/20, 12:30\u202fPM - +91 73554 80774: No\n10/7/20, 12:31\u202fPM - +91 72928 89444: 😅 codechief k long challenge kijiye tab\n10/7/20, 12:32\u202fPM - +91 72928 89444: Alice and Bob have decided to play the game "Rock, Paper, Scissors".\n\nThe game consists of several rounds, each round is independent of each other. In each round, both players show one of the following things at the same time: rock, paper or scissors. If both players showed the same things then the round outcome is a draw. Otherwise, the following rules applied:\n\nif one player showed rock and the other one showed scissors, then the player who showed rock is considered the winner and the other one is considered the loser;\nif one player showed scissors and the other one showed paper, then the player who showed scissors is considered the winner and the other one is considered the loser;\nif one player showed paper and the other one showed rock, then the player who showed paper is considered the winner and the other one is considered the loser.\nAlice and Bob decided to play exactly n rounds of the game described above. Alice decided to show rock a1 times, show scissors a2 times and show paper a3 times. Bob decided to show rock b1 times, show scissors b2 times and show paper b3 times. Though, both Alice and Bob did not choose the sequence in which they show things. It is guaranteed that a1+a2+a3=n and b1+b2+b3=n.\n\nYour task is to find two numbers:\n\nthe minimum number of round Alice can win;\nthe maximum number of rounds Alice can win.\nInput\nThe first line of the input contains one integer n (1≤n≤109) — the number of rounds.\n\nThe second line of the input contains three integers a1,a2,a3 (0≤ai≤n) — the number of times Alice will show rock, scissors and paper, respectively. It is guaranteed that a1+a2+a3=n.\n\nThe third line of the input contains three integers b1,b2,b3 (0≤bj≤n) — the number of times Bob will show rock, scissors and paper, respectively. It is guaranteed that b1+b2+b3=n.\n\nOutput\nPrint two integers: the minimum and the maximum number of rounds Alice can win.\n\nInput\n479 178 29\n11 145 530\noutput\n22 334\n10/7/20, 12:32\u202fPM - +91 72928 89444: Ye question solve kijiye, codeforces k hi h\n10/7/20, 12:33\u202fPM - +91 72928 89444: Pachpan p based h😅\n10/7/20, 12:44\u202fPM - +91 70461 77123: Yes🤕\n10/7/20, 1:25\u202fPM - +91 72928 89444: <Media omitted>\n10/7/20, 1:25\u202fPM - +91 72928 89444: means pattern prog and all?\n10/7/20, 2:47\u202fPM - +91 70461 77123: Ha\n10/7/20, 2:59\u202fPM - +91 70115 09528: <Media omitted>\n10/7/20, 3:01\u202fPM - +91 91238 47093: Just count number of 0s 1s and 2s and print accordingly\n10/7/20, 3:02\u202fPM - +91 70115 09528: it is dutch flag algorithm\n10/7/20, 3:02\u202fPM - +91 70115 09528: do tthe same\n10/7/20, 4:15\u202fPM - +91 84016 67552 joined using a

In [ ]:
file_data = file_data.replace('\u202f',' ')

In [ ]:

# 18/5/24, 9:41 -

pattern = r'\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{1,2}\s[AP]M\s-\s'

message = re.split(pattern,file_data)[1:]

message[1:20]

['+91 94088 93107 created group "Competitive Programmers"\n',
 "You joined using this group's invite link\n",
 '+91 72928 89444: yes\n',
 '+91 72928 89444: C. option\n',
 '+91 72928 89444: O(nlogn)\n',
 '+91 72928 89444: how n^2 bhaia\n',
 '+91 72928 89444: <Media omitted>\n',
 '+91 70115 09528: bhai koi h yha pe jo codechef pe practice krta ho or NZEC  error ajate h hr program m uska ya na ae to wrong answr ata h\n',
 '+91 72928 89444: question no\n',
 '+91 98499 81675: B\n',
 '+91 98347 58456: Ohh... This is right\n',
 "+91 95407 65311: #include <iostream>\nusing namespace std;\n\nint main() {\n    int t;\n    cin>>t;\n    while(t--){\n        long long int n,k;\n        cin>>n>>k;\n        int arr[1000];\n        for (int i=0;i<n;i++){\n            cin>>arr[i];\n        }\n        \n        for(int i=0;i<n;i++){\n            if(arr[i]%k==0){\n                cout<<'1';\n            }\n            else{\n                cout<<'0';\n            }\n        }\n    }\n\treturn 0;\n}\n",
 '+91 95407 65311: whats wrong with this code?\n',
 '+91 95407 65311: cant find any error but there is apparently\n',
 '+91 95407 65311: https://www.codechef.com/problems/CHEFSTEP\n',
 '+91 95407 65311: for this problem\n',
 '+91 63044 49114: Cout << "1"\n',
 '+91 95407 65311: yeah tried thst too\n',
 '+91 95407 65311: #include <iostream>\nusing namespace std;\n\nint main() {\n    int t;\n    cin>>t;\n    while(t--){\n        long long int n,k;\n        cin>>n>>k;\n        int arr[1000];\n        for (int i=0;i<n;i++){\n            cin>>arr[i];\n        }\n        \n        for(int i=0;i<n;i++){\n            if(arr[i]%k==0){\n                cout<<"1";\n            }\n            else{\n                cout<<"0";\n            }\n        }\n    }\n\treturn 0;\n}\n']

In [ ]:
dates = re.findall(pattern,file_data)

dates[1:10]

['1/28/20, 9:45 PM - ',
 '10/6/20, 7:09 PM - ',
 '10/6/20, 7:10 PM - ',
 '10/6/20, 7:10 PM - ',
 '10/6/20, 7:10 PM - ',
 '10/6/20, 7:12 PM - ',
 '10/6/20, 7:13 PM - ',
 '10/6/20, 8:03 PM - ',
 '10/6/20, 8:09 PM - ']

In [ ]:
len(message), len(dates)

(18941, 18941)

In [ ]:
data = pd.DataFrame({'user_message':message,'message_dates':dates})

data.head()

,user_message,message_dates
0,"Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. *Learn more*\n","10/6/20, 7:09 PM -"
1,"+91 94088 93107 created group ""Competitive Programmers""\n","1/28/20, 9:45 PM -"
2,You joined using this group's invite link\n,"10/6/20, 7:09 PM -"
3,+91 72928 89444: yes\n,"10/6/20, 7:10 PM -"
4,+91 72928 89444: C. option\n,"10/6/20, 7:10 PM -"

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18941 entries, 0 to 18940
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   user_message   18941 non-null  object
 1   message_dates  18941 non-null  object
dtypes: object(2)
memory usage: 296.1+ KB

In [ ]:
data['message_dates'] = (data['message_dates'].str.replace(' -',' ',regex=False).str.strip())

In [ ]:
data['message_dates'].iloc[0]

'10/6/20, 7:09 PM'

In [ ]:
# 10/6/20, 7:09 PM

data['message_dates'] = pd.to_datetime(data['message_dates'],format= '%m/%d/%y, %I:%M %p')

KeyError: 'message_dates'

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18941 entries, 0 to 18940
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   user_message   18941 non-null  object
 1   message_dates  18941 non-null  datetime64[ns]
dtypes: datetime64[ns](1), object(1)
memory usage: 296.1+ KB

In [ ]:
data.rename(columns={'message_dates': 'date'},inplace=True)

In [ ]:
data.head(10)

,user_message,date
0,"Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. *Learn more*\n",2020-10-06 19:09:00
1,"+91 94088 93107 created group ""Competitive Programmers""\n",2020-01-28 21:45:00
2,You joined using this group's invite link\n,2020-10-06 19:09:00
3,+91 72928 89444: yes\n,2020-10-06 19:10:00
4,+91 72928 89444: C. option\n,2020-10-06 19:10:00
5,+91 72928 89444: O(nlogn)\n,2020-10-06 19:10:00
6,+91 72928 89444: how n^2 bhaia\n,2020-10-06 19:12:00
7,+91 72928 89444: <Media omitted>\n,2020-10-06 19:13:00
8,+91 70115 09528: bhai koi h yha pe jo codechef pe practice krta ho or NZEC error ajate h hr program m uska ya na ae to wrong answr ata h\n,2020-10-06 20:03:00
9,+91 72928 89444: question no\n,2020-10-06 20:09:00

In [ ]:
data['user_message'][:5]

0    Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. *Learn more*\n
1                                                                   +91 94088 93107 created group "Competitive Programmers"\n
2                                                                                 You joined using this group's invite link\n
3                                                                                                      +91 72928 89444: yes\n
4                                                                                                +91 72928 89444: C. option\n
Name: user_message, dtype: object

In [ ]:
user = []
message = []

for message in data['user_message']:
  entry = re.split(r'([\w\W+?]):\s',message)
  print(entry[1:])

[]
[]
[]
['4', 'yes\n']
['4', 'C. option\n']
['4', 'O(nlogn)\n']
['4', 'how n^2 bhaia\n']
['4', '<Media omitted>\n']
['8', 'bhai koi h yha pe jo codechef pe practice krta ho or NZEC  error ajate h hr program m uska ya na ae to wrong answr ata h\n']
['4', 'question no\n']
['5', 'B\n']
['6', 'Ohh... This is right\n']
['1', "#include <iostream>\nusing namespace std;\n\nint main() {\n    int t;\n    cin>>t;\n    while(t--){\n        long long int n,k;\n        cin>>n>>k;\n        int arr[1000];\n        for (int i=0;i<n;i++){\n            cin>>arr[i];\n        }\n        \n        for(int i=0;i<n;i++){\n            if(arr[i]%k==0){\n                cout<<'1';\n            }\n            else{\n                cout<<'0';\n            }\n        }\n    }\n\treturn 0;\n}\n"]
['1', 'whats wrong with this code?\n']
['1', 'cant find any error but there is apparently\n']
['1', 'https://www.codechef.com/problems/CHEFSTEP\n']
['1', 'for this problem\n']
['4', 'Cout << "1"\n']
['1', 'yeah tried thst too\n']
['1', '#include <iostream>\nusing namespace std;\n\nint main() {\n    int t;\n    cin>>t;\n    while(t--){\n        long long int n,k;\n        cin>>n>>k;\n        int arr[1000];\n        for (int i=0;i<n;i++){\n            cin>>arr[i];\n        }\n        \n        for(int i=0;i<n;i++){\n            if(arr[i]%k==0){\n                cout<<"1";\n            }\n            else{\n                cout<<"0";\n            }\n        }\n    }\n\treturn 0;\n}\n']
['1', 'still giving wromg ans\n']
['4', 'What is the error your getting\n']
['4', 'Than check ur logic\n']
['1', 'wrong ans\n']
['1', 'ya got it, i forgot putting /n in the end\n']
['0', 'Did u made it with flutter bro\n']
['4', 'Yes\n']
['7', 'Hi\n']
['3', 'Hii\n']
['3', 'How you guys manage both dev and CP?\n']
[]
['2', 'DM to buy any premium accounts in cheapest rates.\n*(Accounts like :- LeetCode , Netflix , Amazon Prime and many more)*\n\n\nhttps://chat.whatsapp.com/IM9u21HdXqT54H4HokQ2vx\n\nJoin for more exciting offers.\n']
['7', 'Just create time...\n']
['3', 'Normally I get max to max 5 hours after college\n']
['7', 'Just break it down ....2 for web dev then u rest for 1 hour then the other 2 for cp\n']
['7', 'Or u can use 1 and half hour each and use d remaining 2 hours for rest\n']
['3', 'Okk\n']
['3', 'Where are you from?\n']
['4', 'me 3 hrs\n']
['4', '8am to 6 pm😖\n']
['3', 'Sad🥺🥺🥺🥺\n']
[]
['3', 'I come home by 5 pm start studying from 6:30 to 12:00\n']
['4', '🤩👍 great\n']
['3', 'And 10:00 to 10:30 dinner\n']
['4', 'i give 3hrs for coding and 3 hrs for cgpa😅\n']
['4', '<Media omitted>\n']
['4', 'adding sq one\n']
['4', 'just give me little hint\n']
['4', 'whether the complexity of problem could be less that n^2 or not\n']
['4', 'anyone doing CodeChef  long challenge\n']
['4', 'This message was deleted\n']
['4', 'https://www.codechef.com/OCT20B/problems/ADDSQURE\n']
['3', 'You study everyday for college studies!!!😶😶\n']
[]
['1', 'Anyone who has done the second question of long challenge and is awake?\n']
['4', 'Alice and Bob have decided to play the game "Rock, Paper, Scissors".\n\nThe game consists of several rounds, each round is independent of each other. In each round, both players show one of the following things at the same tim', 'e', 'rock, paper or scissors. If both players showed the same things then the round outcome is a draw. Otherwise, the following rules applie', 'd', '\nif one player showed rock and the other one showed scissors, then the player who showed rock is considered the winner and the other one is considered the loser;\nif one player showed scissors and the other one showed paper, then the player who showed scissors is considered the winner and the other one is considered the loser;\nif one player showed paper and the other one showed rock, then the player who showed paper is considered the winner and the other one is considered the loser.\nAlice and Bob decided to play exactly n rounds of the game described above. Alice decided to show rock a1 times, show scissors a2 times and show paper a3 times. Bob decided to show rock b1 times, show scissors b2 times and show paper b3 times. Though, both Alice and Bob did not choose the sequence in which they show things. It is guaranteed that a1+a2+a3=n and b1+b2+b3=n.\n\nYour task is to find two number', 's', '\nthe minimum number of round Alice can win;\nthe maximum number of rounds Alice can win.\nInput\nThe first line of the input contains one integer n (1≤n≤109) — the number of rounds.\n\nThe second line of the input contains three integers a1,a2,a3 (0≤ai≤n) — the number of times Alice will show rock, scissors and paper, respectively. It is guaranteed that a1+a2+a3=n.\n\nThe third line of the input contains three integers b1,b2,b3 (0≤bj≤n) — the number of times Bob will show rock, scissors and paper, respectively. It is guaranteed that b1+b2+b3=n.\n\nOutput\nPrint two integer', 's', 'the minimum and the maximum number of rounds Alice can win.\n']
['4', '686\n479 178 29\n11 145 530\noutputCopy\n22 334\n']
['4', '<Media omitted>\n']
['4', 'Try this\n']
['4', 'Yes\n']
['4', '<Media omitted>\n']
['4', 'Till 4th done\n']
['4', '6th only thought\n']
['4', "But it's very lengthy\n"]
['6', 'N**2 works here\n']
['6', 'For partial marks\n']
['6', 'I hv done it\n']
['4', '🤩👍\n']
['0', 'Bro where u learnt it\n']
['2', "write a series of python statement that will first as the user to type today's exchange rate between US dollars and Euro next as the user to type a value in dollars finally print the equivalentvalue in euros\n"]
['2', 'Anyone give the solution for this\n']
['4', '<Media omitted>\n']
['4', 'Just do unity method\n']
['3', 'Where can I learn theory of computation??? On youtube\n']
['3', 'Which YouTube videos are good\n']
['9', 'Sanchit is best for T.O.C\n']
['9', 'Knowledge Gate channel\n']
['3', 'Okay👍\n']
['9', '10^5 mein O(n) will give tle?\n']
['3', 'No\n']
[]
['5', 'easy bro..........\n']
['5', '#include <iostream>\nusing namespace std;\n\n\nint main()\n{\n    cout << "Hello World!\\n";\n    cout << "hello sir would you please let me know the value of 1 dollar in euros";\n    int  cash_d;\n    float rate,cash_e;\n    cin >> rate;\n    cout << "enter amount of dollar to convert it in euros";\n    cin >> cash_d;\n    cash_e = cash_d / rate;\n    cout << "your " << cash_d << " dollars in euros are" << cash_e;\n}\n']
['5', 'i have just made it a little user friendly by adding some statements u can remove it though\n']
[]
['1', '<Media omitted>\n']
['4', 'Yes😅\n']
['4', '<Media omitted>\n']
['4', 'If n is no. Of vertices\n']
['4', 'Q8.\n']
['3', 'Bhai ye konse subject ka hai\n']
['4', '<Media omitted>\n']
['4', 'Q9,b part\n']
['4', 'Or bhaia,\n Q9,a part thoda explain kijiye\n']
['4', 'Wo question smjh nhi aa rha\n']
['4', 'Q9 b.)²\n']
['4', '2 is ans\n']
['3', '👆🏻\n']
['4', 'Discrete mathematics\n']
['3', 'Okay\n']
['3', 'Programming related topic haina\n']
['4', 'Coding k liye important h,\nLogical subject h\n']
['3', 'Ohh\n']
['4', 'Mast logic lagta h isse, help milta h\n']
['3', 'Okay mai diploma ka student hu to ye subject kar sakta kya ab\n']
['4', 'Jaise no. Of rectangle made from 8 lines\n']
['4', 'Are bhai subject padhne k liye degree kahan important h\n']
['4', '🤩\n']
['4', 'Araam se padh sakte h\n']
['4', '😇👍\n']
['4', 'Maza ayega\n']
['4', 'Isme\n']
['3', 'Okay thanks😁\n']
['3', 'Links hai kya\n']
['3', 'Sounds great🙄\n']
['4', 'Paheli type lagta h😅\n']
['3', 'Kuch aapke pass\n']
['4', "Coursera I'd h\n"]
['4', 'Du apko?\n']
['3', 'Ha dedo\n']
['4', '70 courses enrolled h\n']
['4', '😅\n']
['4', 'Link vejta hu\n']
['4', 'Personally\n']
['3', 'Ha okay\n']
['4', 'Ap kon se yr  m h\n']
['3', '3rd year\n']
['4', '🙏\n']
['4', '3sem m hu abhi,hume to start hi krwaya gya h\n']
['4', 'Ap kisi aur knowledgeable bhaia se guide le liye\n']
['4', 'Mere pas khud adha knowledge h😅\n']
['4', 'Waise link vejta hu apko👍\n']
['3', 'Okay 👍 aap Coursera ke courses bhej dijiye\n']
['3', 'Ha thanks 😊\n']
['4', '😇🙏\n']
['4', 'Are main junior hu\n']
['4', '😂\n']
['3', 'Aap ye khud kar rahe hai ki college walo ne info di\n']
['3', 'Hame college wale itni info nahi dete\n']
['4', "Ap GitHub students I'd k through le sakte h\n"]
['3', 'Cp ke baare mai\n']
['4', "Bs college I'd k request kijiye ap college se\n"]
['4', "Fir us I'd se\n"]
['4', '1. Microsoft 365\n2. GitHub students pack\n3. Amzaon students pack\n']
['4', 'Sab free🤩\n']
['4', 'Bohot kaam k h student id\n']
['3', 'Okay 👍 try karna padega\n']
['4', '😇hmm\n']
['3', '+ coursera courses.\n']
['4', 'Ab nhi 30 September tak hi tha\n']
['3', 'Oh🤕\n']
['4', 'Maine isi liye 70+ courses enroll kr liya tha\n']
['4', '😅\n']
['4', 'Ab 2 mahine tak padh sakte h\n']
['4', "Don't worry password v de dunga\n"]
['4', 'Agar chahiye to\n']
['4', '<Media omitted>\n']
['4', '<Media omitted>\n']
['1', 'Bhai exam me likhna hai kal exam le rha clg wala assignment based so thoda bna ke do na jo direct chap du 😁🙏🙏 padha nai hu ye topic aur tym v nai h isly\n']
['3', 'Mere pas bhi id ha\nApril May tak kiya badme 6od diya\n']
['4', 'Oo to padh to free m sakte h, bs certificate k liye pay krna padta h\n']
['4', 'Bs knowledge k liye padhiye, certificate kya kijiyega waise v\n']
['4', 'Free h\n']
['4', 'Enroll kr lijiyega\n']
['4', 'Bhaia direct ans hi likhna h\n']
['3', 'Financial aid option hoga\n']
['3', 'Na bro\n']
['3', 'Coursera course bas start krne ke liye h...\nBadme useful nai lagta.\n']
['4', 'Apko agar samjh n derivation to ,call kijiye main samjhane k try krunga\n']
['4', 'Ha,direct likha hua ayega,learn without certificate\n']
['4', 'Ha book ya online sites bata deta hu\n']
['5', 'Someone please send me best course for git and GitHub\n']
['3', 'Means full beginers ho tab course krke sikh lene ka.badme to khud hi krna padta h\n']
['4', 'Fir wo bana lijiyega\n']
['4', 'Ok\n']
['4', '[FreeCourseSite.com] Udemy - The Complete 2020 Web Development Bootcamp\n']
[]
['4', '<Media omitted>\n']
['4', 'Is mahila ne sikhaya h,\n']
['4', 'Isse sikh sakte h\n']
['4', 'Ye download link h\n']
['4', 'Search kijiye\nhttp://FreeCourseSite.com\n']
['4', 'Is site p\n']
['5', 'It tells all about git and GitHub?\n']
['4', '👍sahi baat , practice to khud se hi krna padta h\n']
['4', 'Aur v bohot sara\n']
['5', 'Oh okay thanks 😃\n']
['4', 'Ye v ek part h isme\n']
['4', '👍\n']
['4', 'Carrierride.com\nGeeksforgeeks.com\nCompscibits.com\nLearnerindia.com\nGkseries.com\nCs-mcqs.blogspot.com\n']
['4', 'Ye sab site solve kijiye, \nAche h sare😅\n']
['4', 'Is codeforces down?\n']
['5', 'Yup\n']
['4', 'Kl raat 2 bje se hi h😪\n']
['4', '3 bje tk try kiye fir soo gye\n']
['4', 'Abhi tk nhi thik hua?\n']
['4', 'No\n']
['4', '😅 codechief k long challenge kijiye tab\n']
['4', 'Alice and Bob have decided to play the game "Rock, Paper, Scissors".\n\nThe game consists of several rounds, each round is independent of each other. In each round, both players show one of the following things at the same tim', 'e', 'rock, paper or scissors. If both players showed the same things then the round outcome is a draw. Otherwise, the following rules applie', 'd', '\nif one player showed rock and the other one showed scissors, then the player who showed rock is considered the winner and the other one is considered the loser;\nif one player showed scissors and the other one showed paper, then the player who showed scissors is considered the winner and the other one is considered the loser;\nif one player showed paper and the other one showed rock, then the player who showed paper is considered the winner and the other one is considered the loser.\nAlice and Bob decided to play exactly n rounds of the game described above. Alice decided to show rock a1 times, show scissors a2 times and show paper a3 times. Bob decided to show rock b1 times, show scissors b2 times and show paper b3 times. Though, both Alice and Bob did not choose the sequence in which they show things. It is guaranteed that a1+a2+a3=n and b1+b2+b3=n.\n\nYour task is to find two number', 's', '\nthe minimum number of round Alice can win;\nthe maximum number of rounds Alice can win.\nInput\nThe first line of the input contains one integer n (1≤n≤109) — the number of rounds.\n\nThe second line of the input contains three integers a1,a2,a3 (0≤ai≤n) — the number of times Alice will show rock, scissors and paper, respectively. It is guaranteed that a1+a2+a3=n.\n\nThe third line of the input contains three integers b1,b2,b3 (0≤bj≤n) — the number of times Bob will show rock, scissors and paper, respectively. It is guaranteed that b1+b2+b3=n.\n\nOutput\nPrint two integer', 's', 'the minimum and the maximum number of rounds Alice can win.\n\nInput\n479 178 29\n11 145 530\noutput\n22 334\n']
['4', 'Ye question solve kijiye, codeforces k hi h\n']
['4', 'Pachpan p based h😅\n']
['3', 'Yes🤕\n']
['4', '<Media omitted>\n']
['4', 'means pattern prog and all?\n']
['3', 'Ha\n']
['8', '<Media omitted>\n']
['3', 'Just count number of 0s 1s and 2s and print accordingly\n']
['8', 'it is dutch flag algorithm\n']
['8', 'do tthe same\n']
[]
['5', 'how to do such types of questions??\n']
[]
[]
['4', 'We have to check whether scissors and  rock of Bob can destroy or nullify  Alice max event\n']
['5', 'listen help me out here........ ihave succesflly made the code for finding out the maximum wins but i am facing trouble finding the minimum wins\n']
['0', 'Guys iam new to codechef how do i start??\n']
['3', 'Same question?please someone answer\n']
['9', 'You are new to codechef or new to competitive programming?\n']
['0', 'New to codechef\n']
['0', 'I have practised on hackerrank\n']
['0', 'Before\n']
['5', '.\n']
['4', 'Bhaia , minimum case hi to hard part h\n']
['4', '#include<iostream>\n#include<algorithm>\n#include<vector>\nusing namespace std;\n#define ll long long int\nint main()\n{\n   ios_base::sync_with_stdio(false);\n   cin.tie(NULL);\n   cout.tie(NULL);\n   ll a[3],b[3];\n   ll t;\n   cin>>t;\n\n   while(t--)\n    {\n\n    ll n;\n   cin>>n;\n   for(int i=0; i<3; i++)\n      cin>>a[i];\n\n    for(int i=0;i<3;i++)\n      cin>>b[i];\n\n    ll max=0,min=0;\n    for(int i=0;i<3;i++)\n       if(a[i%3] > b[(i+1)%3])\n           max = max + b[(i+1)%3];\n       else\n           max = max + a[i%3];\n\n\n      //Minimum wins\n      int i=0;\n      for(i=0; i<3; i++)\n      {\n\n      if((b[i%3] + b[(i+1)%3]) < a[(i+1)%3])\n        {\n          min=a[(i+1)%3] - (b[i%3] + b[(i+1)%3]);\n          break;\n        }\n\n     }\n       cout<<min<<" "<<max;\n    }\n}\n']
['4', 'You should try first\n']
['5', 'Ek ghanta ho gaya yaar😂\n']
['4', '😎🙌\n']
['4', '(b[i%3] + b[(i+1)%3]) < a[(i+1)%3])\n']
['4', 'Solve using cyclic way\n']
['4', '1st of A to\n2nd of B\n']
['4', '2nd of A to\n3rd of B\n']
['1', 'Which year?\n']
['4', '3rd semester\n']
['5', '🙏\n']
['4', 'Kya bhaia kuch v😂\n']
['5', 'Senior ho aap to... I just passed 12th🙏\n']
['4', 'Bhai jee mains to maine v jiya h\n']
['4', '😅\n']
['4', 'Same hi h\n']
['5', 'Hmm\n']
['4', 'College kon sa mil rha h\n']
['4', '?\n']
['5', 'DTU lower branches , IP mei MAIT and Msit\n']
['5', 'U from which colleg?\n']
['4', 'Halawai chacha k yahan se\n']
['4', 'LOVELY PROFESSIONAL UNIVERSITY\n']
['1', '😂\n']
['5', '👀🤭 seriously?\n']
['4', 'Dtu le le bhai\n']
['1', 'Same\n']
['4', 'Ap v 12 th pass\n']
['1', 'Yup\n']
['4', 'College\n']
['4', '?\n']
['4', 'Decided?\n']
['1', 'May be will join nit jamshedpur cse\n']
['4', '🤩👍\n']
['4', 'Kitta rank h\n']
['5', 'Hmm pr engineering physics ya instrumental ya production milegi.... But I hv decided krni coding hi h... So kind of in a problem\n']
['4', 'BIT MESHRA LE LE BHAI\n']
['1', '9391\n']
['4', '😎\n']
['4', 'Bit meshra sahi h tab to\n']
['5', 'Why not DTU ?\n']
['4', 'Dtu m 3 branches h\n']
['4', 'EEE\n']
['4', 'Ece\n']
['4', 'This message was deleted\n']
['4', 'Cse\n']
['4', 'Koi v le le wahan p\n']
['4', 'Sab sahi h\n']
['2', 'You can have higher nit than nit jamshedpur\nLike nit Silchar, Durgapur or Jalandhar\n\nI think you should try for that\n']
['4', 'Outside Delhi hoga obviously\n']
['1', 'Yes\n']
['1', 'Par cse nhi milega na?\n']
['2', 'Category ?\n']
['1', 'Gen\n']
['2', 'EWS ??\n']
['1', 'Nope\n']
['2', 'Ohh\nBut can try\n']
['5', '<Media omitted>\n']
['5', '@\u2068~Bhaskar Kumar\u2069\n']
['4', 'nhi nhi tino m kabhi ek hi baar ye condition sah ho paye ga\n']
['4', 'sara test cases mera v nhi hua h\n']
['4', 'or sahi krna h\n']
['4', 'pehle long challenge kr lete h\n']
['5', 'Ach.. ek baar += lagake dekho\n']
['4', 'uske baad ispe dimag lagayenge\n']
['4', 'hm\n']
['4', 'krte h\n']
['4', 'try\n']
['5', 'Hmm\n']
['4', 'long challenge kr rhe ho\n']
['5', 'Kya hota hai voh?😅\n']
['5', 'I am not a pro like you .... just a beginner😅\n']
['4', 'This message was deleted\n']
['4', 'pata chal jayega\n']
['4', 'codechef\n']
['4', 'kholo\n']
['6', 'Villanet kiya tumne?\n']
['6', 'partially?\n']
['4', 'nhi idea h bs\n']
['4', 'tree h n usme\n']
['5', '<Media omitted>\n']
['4', 'dikkat ho rha h\n']
['4', 'upcoming\n']
['4', 'challenges\n']
['4', 'm\n']
['4', 'jao\n']
['4', 'oct long\n']
['5', '<Media omitted>\n']
['4', 'yea boy\n']
['4', '🤩👍\n']
['4', 'go for it\n']
['5', 'Hmm got it thanks ☺️ sir\n']
['4', 'are bhai\n']
['4', 'sir kya h\n']
['4', 'budhha bana de rhe ho\n']
['4', 'sab bhai hi h\n']
['4', '😂\n']
['5', 'Experienced bana rha hu😅\n']
['5', 'Hmm\n']
['4', 'kahan se ho\n']
['5', 'Delhi\n']
['4', 'dtu fix🥳\n']
['5', "😅 let's see what happens\n"]
['4', 'B-H-A-G-A-L-P-U-R\n']
['4', 'Lnmit 😌\n']
['4', 'BIHAR\n']
['4', 'Mera thikana\n']
['4', 'from\n']
['5', "Haaan that's the best\n"]
['5', 'Oh nice 💯\n']
['4', 'Yep😌\n']
['4', '👍\n']
['5', 'Oh k\n']
['1', 'Hey same here😂\n']
['4', 'bhai bhai\n']
['1', '😂😂I know\n']
['5', '<Media omitted>\n']
['5', 'This is for kotlin programmer\n']
['4', 'abbe konsa data h ye\n']
['6', 'Pm or pa?\n']
['5', 'Average hai to annum hi hogi\n']
['6', 'Android studio me c++ ka option hota hai kya?\n']
[]
['7', 'Nigeria\n']
['4', "i don't think so 😶\n"]
['4', 'java\n']
['4', 'kotlin\n']
['6', '👍🏻👍🏻\n']
['3', 'Suggest some python based final year Projects plzz🙏🏻🙏🏻\n']
['3', 'Yes some unique ones\n']
['0', 'Speech to text related\n']
['3', 'Voice recognition\n']
['0', 'Hmm\n']
['0', '<Media omitted>\n']
['6', 'This message was deleted\n']
['8', '<Media omitted>\n']
['4', 'Mingw setup kr lo bhai\n']
['4', 'Gcc missing hoga\n']
['4', 'Kon sa IDE h ?\n']
['4', 'Size of k is\n']
['4', 'Less than length of array\n']
['4', 'Count cannot accommodate more than k elements\n']
['0', 'Sublime text\n']
['4', 'Ok\n']
['4', 'Check path\n']
['4', 'Environmental setup\n']
['4', 'Or install mingw\n']
['4', 'Gcc\n']
['0', 'Your file extension is .txt\n']
['0', 'as it seems to be\n']
['8', 'k+1 ka count bnana hoga???\n']
['4', 'K user dal rha h kya\n']
['4', 'Error to isliye hi aa rha h\n']
['4', 'Count k size array se kum h\n']
['4', 'Wo accommodate nhi kr paa rha h pure array ko\n']
['4', 'Change extension to .cpp\n']
['4', 'Or\n']
['4', 'https://youtu.be/sXW2VLrQ3Bs\n']
['4', 'See this video\n']
['4', 'Got it\n']
['4', 'If a[i]=999\n']
['4', 'Then you are adding 1 to ctr[999]\n']
['4', "It's not practical\n"]
['4', 'I think you want to find Freq of each element in an array\n']
['4', 'You should go with set in STL\n']
['4', 'Or in collection.java\n']
['4', 'In C++ u can use map or dictionary too\n']
['8', 'ho gya bhai solve thanks🙂\n']
['4', '👍\n']
['4', 'Kaise sahi kiye\n']
[]
['8', '<Media omitted>\n']
[]
['4', 'Ye fix hu\n']
['8', 'nhi yr\n']
['4', 'K+1\n']
['4', '👍\n']
['8', 'yes😂\n']
['4', 'Lekin array m agar bada elements aa jaye jaise\n']
['4', '98,67,189,999\n']
['4', 'Tab error aa jayega😳\n']
['8', 'bhai counting sort is form small elements\n']
['4', 'Tb shi h\n']
['4', 'Waise koi aur method h\n']
['4', '?\n']
['4', 'Freq of each element niklane k ?\n']
['8', 'depends on tine complexity\n']
['8', 'time*\n']
['4', 'AMONG US 😅 KOI KHELEGA\n']
['3', 'Abhi nai😅\n']
['4', '😂👍\n']
['4', 'Isme kya problem h\n']
['8', 'bhai terpe tym h yha hmare L lge h 😂\n']
['4', 'Line no ?\n']